import { unwrap } from '@sectile/core/result';
import { createTerminalTemporalController, createTerminalTemporalFacadeConnection, type TerminalTemporalController, type TerminalTemporalResult } from './internal/result.js';
import type { RevisionSnapshot } from '@sectile/core/revision';
import type { TextEditingState, TextEvent, TextSelectionInput } from '@sectile/core/text';
import type { DateRange } from '@sectile/temporal/date-field';
import { applyDateRangeFieldEvent, tryCreateDateRangeFieldState, type DateRangeFieldCommand, type DateRangeFieldEndpoint, type DateRangeFieldEvent, type DateRangeFieldPolicies, type DateRangeFieldState } from '@sectile/temporal/date-range-field';
import { type FacadeConnection } from '@sectile/core/adapter-runtime';
import { toTerminalTextInput } from './internal/text-input.js';
import { toTextEvent } from './text.js';
import type { TerminalKeyboardInput } from './keyboard.js';

export interface DateRangeFieldOptions { readonly value?: DateRange | null; readonly defaultValue?: DateRange | null; readonly startInputState?: TextEditingState; readonly defaultStartInputState?: TextEditingState; readonly endInputState?: TextEditingState; readonly defaultEndInputState?: TextEditingState; readonly policies?: DateRangeFieldPolicies; readonly disabled?: boolean; readonly readOnly?: boolean; readonly required?: boolean; readonly onValueChange?: (value: DateRange | null) => void; readonly onStartInputStateChange?: (value: TextEditingState) => void; readonly onEndInputStateChange?: (value: TextEditingState) => void; readonly onUpdate?: () => void }

export type DateRangeFieldValueChangeHandler = NonNullable<DateRangeFieldOptions['onValueChange']>;
export type DateRangeFieldStartInputStateChangeHandler = NonNullable<DateRangeFieldOptions['onStartInputStateChange']>;
export type DateRangeFieldEndInputStateChangeHandler = NonNullable<DateRangeFieldOptions['onEndInputStateChange']>;
export type DateRangeFieldUpdateHandler = NonNullable<DateRangeFieldOptions['onUpdate']>;
export interface DateRangeFieldControlledValues { readonly value?: DateRange | null; readonly startInputState?: TextEditingState; readonly endInputState?: TextEditingState }
export interface DateRangeFieldConnection { getSnapshot(): RevisionSnapshot<DateRangeFieldState>; getValue(): DateRange | null; getText(endpoint: DateRangeFieldEndpoint): string; syncControlledValues(values: DateRangeFieldControlledValues): TerminalTemporalResult<RevisionSnapshot<DateRangeFieldState>>; handleEvent(event: DateRangeFieldEvent): boolean; handleKeyboardInput(input: TerminalKeyboardInput): boolean }
export function createDateRangeField(options: DateRangeFieldOptions = {}): FacadeConnection<DateRangeFieldConnection> { return unwrap(tryCreateDateRangeField(options)); }
export function tryCreateDateRangeField(options: DateRangeFieldOptions = {}): TerminalTemporalResult<FacadeConnection<DateRangeFieldConnection>> { return createTerminalTemporalFacadeConnection(options, construct); }
function construct(options: DateRangeFieldOptions): TerminalTemporalResult<DateRangeFieldConnection> {
  const controlled = { value: options.value !== undefined, start: options.startInputState !== undefined, end: options.endInputState !== undefined };
  const runtime = createTerminalTemporalController<DateRangeFieldState, DateRangeFieldEvent, DateRangeFieldCommand, DateRangeFieldCommand>({
    initial: tryCreateDateRangeFieldState({ value: options.value !== undefined ? options.value : options.defaultValue ?? null, ...optionalInputState('startInputState', options.startInputState ?? options.defaultStartInputState), ...optionalInputState('endInputState', options.endInputState ?? options.defaultEndInputState) }),
    reducer: (state, event) => applyDateRangeFieldEvent(state, event, { ...options.policies, ...(options.required === undefined ? {} : { required: options.required }) }),
    reconcile: (previous, proposed) => tryCreateDateRangeFieldState({ startValue: controlled.value ? previous.start.value : proposed.start.value, endValue: controlled.value ? previous.end.value : proposed.end.value, startInputState: controlled.start ? previous.start.inputState : proposed.start.inputState, endInputState: controlled.end ? previous.end.inputState : proposed.end.inputState, active: proposed.active }),
    notify: (previous, proposed) => { if (previous.start.inputState !== proposed.start.inputState) options.onStartInputStateChange?.(proposed.start.inputState); if (previous.end.inputState !== proposed.end.inputState) options.onEndInputStateChange?.(proposed.end.inputState); },
    toEffect: (command) => command, interaction: options,
  });
  return runtime.ok ? { ok: true, value: new TerminalDateRangeField(options, runtime.value, controlled) } : runtime;
}

function optionalInputState<Key extends 'startInputState' | 'endInputState'>(key: Key, value: TextEditingState | undefined): { readonly [Property in Key]?: TextEditingState } { return value === undefined ? {} : { [key]: value } as { readonly [Property in Key]?: TextEditingState }; }
class TerminalDateRangeField implements DateRangeFieldConnection {
  readonly #options: DateRangeFieldOptions; readonly #runtime: TerminalTemporalController<DateRangeFieldState, DateRangeFieldEvent, DateRangeFieldCommand>; readonly #controlled: { readonly value: boolean; readonly start: boolean; readonly end: boolean };
  public constructor(options: DateRangeFieldOptions, runtime: TerminalTemporalController<DateRangeFieldState, DateRangeFieldEvent, DateRangeFieldCommand>, controlled: { readonly value: boolean; readonly start: boolean; readonly end: boolean }) { this.#options = options; this.#runtime = runtime; this.#controlled = controlled; }
  public getSnapshot(): RevisionSnapshot<DateRangeFieldState> { return this.#runtime.getSnapshot(); }
  public getValue(): DateRange | null { return this.getSnapshot().state.value; }
  public getText(endpoint: DateRangeFieldEndpoint): string { return this.getSnapshot().state[endpoint].inputState.snapshot.text; }
  public syncControlledValues(values: DateRangeFieldControlledValues): TerminalTemporalResult<RevisionSnapshot<DateRangeFieldState>> { if (this.#controlled.value !== (values.value !== undefined) || this.#controlled.start !== (values.startInputState !== undefined) || this.#controlled.end !== (values.endInputState !== undefined)) return { ok: false, error: { class: 'construction', code: 'controlled-shape-mismatch', message: 'Controlled date range field values must preserve their construction-time shape.' } }; const current = this.getSnapshot().state; const result = this.#runtime.replace(tryCreateDateRangeFieldState({ value: this.#controlled.value ? values.value as DateRange | null : current.value, ...optionalInputState('startInputState', this.#controlled.start ? values.startInputState : current.start.inputState), ...optionalInputState('endInputState', this.#controlled.end ? values.endInputState : current.end.inputState), active: current.active })); if (result.ok) this.#options.onUpdate?.(); return result; }
  public handleEvent(event: DateRangeFieldEvent): boolean { const result = this.#runtime.handle(event); if (result.ok) { for (const command of result.commands) if (command.type === 'range-committed') this.#options.onValueChange?.(command.value); this.#options.onUpdate?.(); } return result.ok; }
  public handleKeyboardInput(input: TerminalKeyboardInput): boolean { const endpoint = this.getSnapshot().state.active; if (input.ctrlKey === true || input.altKey === true) return false; if (input.key === 'tab') return this.handleEvent({ type: 'focus', endpoint: endpoint === 'start' ? 'end' : 'start' }); if (input.key === 'enter') return this.handleEvent({ type: 'field', endpoint, event: 'commit' }); if (input.key === 'escape') return this.handleEvent('cancel'); if (input.key === 'up' || input.key === 'down') return this.handleEvent({ type: 'field', endpoint, event: input.key === 'up' ? 'increment-segment' : 'decrement-segment' }); if (input.key === 'left' || input.key === 'right' || input.key === 'home' || input.key === 'end') return this.#move(endpoint, input); const semantic = toTerminalTextInput(this.getSnapshot().state[endpoint].inputState, input); const event = semantic === null ? null : toTextEvent(semantic); return event !== null && this.handleEvent({ type: 'field', endpoint, event: { type: 'text', event } }); }
  #move(endpoint: DateRangeFieldEndpoint, input: TerminalKeyboardInput): boolean { const snapshot = this.getSnapshot().state[endpoint].inputState.snapshot; const selection = snapshot.selection; const focus = input.key === 'home' ? 0 : input.key === 'end' ? snapshot.text.length : input.key === 'left' ? Math.max(0, selection.focusCodeUnitOffset - 1) : Math.min(snapshot.text.length, selection.focusCodeUnitOffset + 1); const next: TextSelectionInput = { anchorCodeUnitOffset: input.shiftKey === true ? selection.anchorCodeUnitOffset : focus, focusCodeUnitOffset: focus }; const event: TextEvent = { type: 'replace', startCodeUnitOffset: focus, endCodeUnitOffset: focus, text: '', selection: next }; return this.handleEvent({ type: 'field', endpoint, event: { type: 'text', event } }); }
}
