import { unwrap } from '@sectile/core/result';
import type { Result } from '@sectile/core';
import type { RevisionSnapshot } from '@sectile/core/revision';
import { compareDateValues, formatDateValue, type DateRange, type DateValue } from '@sectile/core/date-field';
import { createDatePickerMonth, type DatePickerEvent, type DatePickerPolicies } from '@sectile/core/date-picker';
import { applyDateRangePickerEvent, tryCreateDateRangePickerState, type DateRangePickerCommand, type DateRangePickerEvent, type DateRangePickerState } from '@sectile/core/date-range-picker';
import { createFacadeConnection, type FacadeConnection } from './internal/facade.js';
import { createSemanticController, type SemanticController } from './internal/semantic-controller.js';
import type { TerminalKeyboardInput } from './keyboard.js';
import { toDatePickerEvent } from './date-picker.js';

export interface DateRangePickerOptions { readonly policies?: DatePickerPolicies; readonly value?: DateRange | null; readonly defaultValue?: DateRange | null; readonly highlightedValue?: DateValue; readonly defaultHighlightedValue?: DateValue; readonly open?: boolean; readonly defaultOpen?: boolean; readonly disabled?: boolean; readonly readOnly?: boolean; readonly required?: boolean; readonly onValueChange?: (value: DateRange | null) => void; readonly onHighlightedValueChange?: (value: DateValue) => void; readonly onOpenChange?: (open: boolean) => void; readonly onUpdate?: () => void; }
export interface DateRangePickerControlledValues { readonly value?: DateRange | null; readonly highlightedValue?: DateValue; readonly open?: boolean; }
export interface DateRangePickerConnection { getSnapshot(): RevisionSnapshot<DateRangePickerState>; getMonth(): readonly (readonly DateValue[])[]; syncControlledValues(values: DateRangePickerControlledValues): Result<RevisionSnapshot<DateRangePickerState>>; handleEvent(event: DateRangePickerEvent): boolean; handleKeyboardInput(input: TerminalKeyboardInput): boolean; }
export function createDateRangePicker(options: DateRangePickerOptions = {}): FacadeConnection<DateRangePickerConnection> { return unwrap(tryCreateDateRangePicker(options)); }
export function tryCreateDateRangePicker(options: DateRangePickerOptions = {}): Result<FacadeConnection<DateRangePickerConnection>> { return createFacadeConnection(options, construct); }
function construct(options: DateRangePickerOptions): Result<DateRangePickerConnection> { const controls = { value: options.value !== undefined, highlighted: options.highlightedValue !== undefined, open: options.open !== undefined }; const requestedValue = controls.value ? options.value : options.defaultValue; const requestedHighlight = controls.highlighted ? options.highlightedValue : options.defaultHighlightedValue; const requestedOpen = controls.open ? options.open : options.defaultOpen; const initial = tryCreateDateRangePickerState({ ...(requestedValue === undefined ? {} : { value: requestedValue }), calendar: { ...(requestedHighlight === undefined ? {} : { highlighted: requestedHighlight }), ...(requestedOpen === undefined ? {} : { open: requestedOpen }) } }); const runtime = createSemanticController<DateRangePickerState, DateRangePickerEvent, DateRangePickerCommand, DateRangePickerCommand>({ initial, reducer: (state, event) => applyDateRangePickerEvent(state, event, { ...options.policies, ...(options.required === undefined ? {} : { required: options.required }) }), reconcile: (previous, proposed) => tryCreateDateRangePickerState({ value: controls.value ? previous.value : proposed.value, anchor: proposed.anchor, calendar: { ...proposed.calendar, highlighted: controls.highlighted ? previous.calendar.highlighted : proposed.calendar.highlighted, view: controls.highlighted ? previous.calendar.view : proposed.calendar.view, open: controls.open ? previous.calendar.open : proposed.calendar.open } }), notify: (previous, proposed) => { if (rangeKey(previous.value) !== rangeKey(proposed.value)) options.onValueChange?.(proposed.value); if (compareDateValues(previous.calendar.highlighted, proposed.calendar.highlighted) !== 0) options.onHighlightedValueChange?.(proposed.calendar.highlighted); if (previous.calendar.open !== proposed.calendar.open) options.onOpenChange?.(proposed.calendar.open); }, toEffect: (command) => command, interaction: options }); return runtime.ok ? { ok: true, value: new TerminalDateRangePicker(options, runtime.value, controls) } : runtime; }
class TerminalDateRangePicker implements DateRangePickerConnection {
  readonly options: DateRangePickerOptions; readonly runtime: SemanticController<DateRangePickerState, DateRangePickerEvent, DateRangePickerCommand>; readonly controls: { value: boolean; highlighted: boolean; open: boolean };
  public constructor(options: DateRangePickerOptions, runtime: SemanticController<DateRangePickerState, DateRangePickerEvent, DateRangePickerCommand>, controls: { value: boolean; highlighted: boolean; open: boolean }) { this.options = options; this.runtime = runtime; this.controls = controls; }
  public getSnapshot(): RevisionSnapshot<DateRangePickerState> { return this.runtime.getSnapshot(); } public getMonth(): readonly (readonly DateValue[])[] { const state = this.getSnapshot().state.calendar; return createDatePickerMonth(state.view, this.options.policies?.weekStartsOn); }
  public syncControlledValues(values: DateRangePickerControlledValues): Result<RevisionSnapshot<DateRangePickerState>> { if (this.controls.value !== (values.value !== undefined) || this.controls.highlighted !== (values.highlightedValue !== undefined) || this.controls.open !== (values.open !== undefined)) return { ok: false, error: { class: 'construction', code: 'controlled-shape-mismatch', message: 'Controlled date range picker values must preserve their construction-time shape.' } }; const state = this.getSnapshot().state; const highlighted = this.controls.highlighted ? values.highlightedValue as DateValue : state.calendar.highlighted; const result = this.runtime.replace(tryCreateDateRangePickerState({ value: this.controls.value ? values.value as DateRange | null : state.value, anchor: state.anchor, calendar: { highlighted, view: { year: highlighted.year, month: highlighted.month }, viewMode: state.calendar.viewMode, open: this.controls.open ? values.open as boolean : state.calendar.open } })); if (result.ok) this.options.onUpdate?.(); return result; }
  public handleEvent(event: DateRangePickerEvent): boolean { const result = this.runtime.handle(event); if (result.ok) this.options.onUpdate?.(); return result.ok; }
  public handleKeyboardInput(input: TerminalKeyboardInput): boolean { const event: DatePickerEvent | null = toDatePickerEvent(input); return event !== null && this.handleEvent(event); }
}
function rangeKey(value: DateRange | null): string { return value === null ? '' : `${formatDateValue(value.start)}/${formatDateValue(value.end)}`; }
