import type { Result, StableID } from '@sectile/primitives';
import { applyGridEvent, createGrid, createGridState, type Grid, type GridCommand, type GridEditMode, type GridEvent, type GridOptions as StructureGridOptions, type GridPolicies, type GridState } from '@sectile/primitives/grid';
import type { RevisionSnapshot } from '@sectile/primitives/revision';
import type { TerminalKeyboardInput } from './keyboard.js';
import { createSemanticController, type SemanticController } from './internal/semantic-controller.js';

export interface GridOptions<ID extends StableID = StableID> extends StructureGridOptions { readonly rows: readonly (readonly (ID | null)[])[]; readonly value?: ID | null; readonly defaultValue?: ID | null; readonly highlightedValue?: ID | null; readonly defaultHighlightedValue?: ID | null; readonly editMode?: GridEditMode; readonly defaultEditMode?: GridEditMode; readonly policies?: GridPolicies<ID>; readonly disabledItems?: readonly ID[]; readonly onValueChange?: (value: ID | null) => void; readonly onHighlightedValueChange?: (value: ID | null) => void; readonly onEditModeChange?: (mode: GridEditMode) => void; readonly onEditStart?: (id: ID) => void; readonly onEditCommit?: (id: ID) => void; readonly onEditCancel?: (id: ID) => void; readonly onUpdate?: () => void }
export interface GridControlledValues<ID extends StableID = StableID> { readonly value?: ID | null; readonly highlightedValue?: ID | null; readonly editMode?: GridEditMode }
export interface GridConnection<ID extends StableID = StableID> { readonly grid: Grid<ID>; getSnapshot(): RevisionSnapshot<GridState<ID>>; syncControlledValues(values: GridControlledValues<ID>): Result<RevisionSnapshot<GridState<ID>>>; handleEvent(event: GridEvent<ID>): boolean; handleKeyboardInput(input: TerminalKeyboardInput): boolean }

export function createGridControl<ID extends StableID>(options: GridOptions<ID>): Result<GridConnection<ID>> {
  const grid = createGrid(options.rows, options); if (!grid.ok) return grid; const disabled=new Set(options.disabledItems??[]);for(const id of disabled)if(grid.value.positionOf(id)===null)return{ok:false,error:{class:'construction',code:'disabled-item-outside-domain',message:'Every disabled grid cell must exist in the grid.',details:{id}}};const supplied=options.policies?.eligible;const policies:GridPolicies<ID>={...options.policies,eligible:(id)=>!disabled.has(id)&&(supplied?.(id)??true)};const vc=options.value!==undefined,hc=options.highlightedValue!==undefined,ec=options.editMode!==undefined;const selected = options.value !== undefined ? options.value : options.defaultValue ?? null;
  const runtime = createSemanticController<GridState<ID>, GridEvent<ID>, GridCommand<ID>, GridCommand<ID>>({ initial: createGridState(grid.value, { current: options.highlightedValue !== undefined ? options.highlightedValue : options.defaultHighlightedValue ?? null, selected: selected === null ? [] : [selected], anchor: selected, editMode: options.editMode ?? options.defaultEditMode ?? 'navigation' }), reducer: (state, event) => applyGridEvent(grid.value, state, event, policies), reconcile: (previous, proposed) => createGridState(grid.value, { current: hc ? previous.cursor.current : proposed.cursor.current, selected: vc ? previous.selection.selected : proposed.selection.selected, anchor: vc ? previous.selection.anchor : proposed.selection.anchor, editMode: ec ? previous.editMode : proposed.editMode }), notify: (previous, proposed) => { const before = previous.selection.selected[0] ?? null; const after = proposed.selection.selected[0] ?? null; if (before !== after) options.onValueChange?.(after);if(previous.cursor.current!==proposed.cursor.current)options.onHighlightedValueChange?.(proposed.cursor.current);if(previous.editMode!==proposed.editMode)options.onEditModeChange?.(proposed.editMode); }, toEffect: (command) => command });
  if (!runtime.ok) return runtime; return { ok: true, value: new TerminalGrid(options, grid.value, runtime.value,vc,hc,ec) };
}

class TerminalGrid<ID extends StableID> implements GridConnection<ID> {
  public readonly grid: Grid<ID>; readonly #options: GridOptions<ID>; readonly #runtime: SemanticController<GridState<ID>, GridEvent<ID>, GridCommand<ID>>;readonly #vc:boolean;readonly #hc:boolean;readonly #ec:boolean;
  public constructor(options: GridOptions<ID>, grid: Grid<ID>, runtime: SemanticController<GridState<ID>, GridEvent<ID>, GridCommand<ID>>,vc:boolean,hc:boolean,ec:boolean) { this.#options = options; this.grid = grid; this.#runtime = runtime;this.#vc=vc;this.#hc=hc;this.#ec=ec; }
  public getSnapshot(): RevisionSnapshot<GridState<ID>> { return this.#runtime.getSnapshot(); }
  public syncControlledValues(values: GridControlledValues<ID>): Result<RevisionSnapshot<GridState<ID>>> {if(this.#vc!==(values.value!==undefined)||this.#hc!==(values.highlightedValue!==undefined)||this.#ec!==(values.editMode!==undefined))return{ok:false,error:{class:'construction',code:'controlled-shape-mismatch',message:'Controlled grid values must preserve their construction-time shape.'}}; const current = this.getSnapshot().state; const selected = values.value === undefined ? current.selection.selected : values.value === null ? [] : [values.value];const result=this.#runtime.replace(createGridState(this.grid, { current: values.highlightedValue === undefined ? current.cursor.current : values.highlightedValue, selected, anchor: values.value === undefined ? current.selection.anchor : values.value, editMode: values.editMode ?? current.editMode }));if(result.ok)this.#options.onUpdate?.();return result; }
  public handleEvent(event: GridEvent<ID>): boolean {const result=this.#runtime.handle(event);if(result.ok)for(const command of result.commands){if(command.type==='begin-edit')this.#options.onEditStart?.(command.id);else if(command.type==='commit-edit')this.#options.onEditCommit?.(command.id);else if(command.type==='cancel-edit')this.#options.onEditCancel?.(command.id)} this.#options.onUpdate?.(); return true; }
  public handleKeyboardInput(input: TerminalKeyboardInput): boolean { const event = toGridEvent(input, this.getSnapshot().state.editMode); return event === null ? false : this.handleEvent(event); }
}

function toGridEvent(input: TerminalKeyboardInput, editMode: GridEditMode): Extract<GridEvent, string> | null { if (input.ctrlKey) return null; if (editMode === 'editing') { if (input.key === 'enter') return 'commit-edit'; if (input.key === 'escape') return 'cancel-edit'; return null; } if (input.altKey) return null; if (input.key === 'left' || input.key === 'right' || input.key === 'up' || input.key === 'down') return input.key; if (input.key === 'space') return 'select'; if (input.key === 'enter' || input.key === 'edit') return 'start-edit'; return null; }
