import type { Result } from '@sectile/primitives';
import type { RevisionSnapshot } from '@sectile/primitives/revision';
import { applyPinInputEvent, createPinInputState, type PinInputCommand, type PinInputEvent, type PinInputPolicies, type PinInputState } from '@sectile/primitives/pin-input';
import type { TerminalKeyboardInput } from './keyboard.js';
import { createSemanticController, type SemanticController } from './internal/semantic-controller.js';
export interface PinInputOptions { readonly length: number; readonly policies?: PinInputPolicies; readonly disabled?: boolean; readonly readOnly?: boolean; readonly value?: string; readonly defaultValue?: string; readonly onValueChange?: (value: string) => void; readonly onComplete?: (value: string) => void; readonly onUpdate?: () => void }
export interface PinInputConnection { getSnapshot(): RevisionSnapshot<PinInputState>; syncControlledValue(value: string): Result<RevisionSnapshot<PinInputState>>; handleEvent(event: PinInputEvent): boolean; handleKeyboardInput(input: TerminalKeyboardInput): boolean }
export function createPinInput(options: PinInputOptions): Result<PinInputConnection> { const controlled = options.value !== undefined; const runtime = createSemanticController<PinInputState, PinInputEvent, PinInputCommand, PinInputCommand>({ interaction: options, interactionIntent: (event) => event === 'next' || event === 'previous' || (typeof event === 'object' && event.type === 'focus') ? 'navigate' : 'mutate', initial: createPinInputState(options.length, options.value ?? options.defaultValue ?? ''), reducer: (state, event) => applyPinInputEvent(options.length, state, event, options.policies), reconcile: (previous, proposed) => controlled ? createPinInputState(options.length, previous.values) : { ok: true, value: proposed }, notify: (previous, proposed) => { const before = previous.values.join(''); const after = proposed.values.join(''); if (before !== after) options.onValueChange?.(after); }, toEffect: (command) => command }); return runtime.ok ? { ok: true, value: new TerminalPinInputConnection(options, runtime.value, controlled) } : runtime; }
class TerminalPinInputConnection implements PinInputConnection { readonly #options: PinInputOptions; readonly #runtime: SemanticController<PinInputState, PinInputEvent, PinInputCommand>; readonly #controlled: boolean; constructor(options: PinInputOptions, runtime: SemanticController<PinInputState, PinInputEvent, PinInputCommand>, controlled: boolean) { this.#options = options; this.#runtime = runtime; this.#controlled = controlled; } getSnapshot() { return this.#runtime.getSnapshot(); } syncControlledValue(value: string) { if (!this.#controlled) return { ok: false as const, error: { class: 'construction' as const, code: 'controlled-shape-mismatch', message: 'Only a controlled pin input accepts external values.' } }; const result = this.#runtime.replace(createPinInputState(this.#options.length, value)); if (result.ok) this.#options.onUpdate?.(); return result; } handleEvent(event: PinInputEvent) { const result = this.#runtime.handle(event); if (result.ok) { for (const effect of result.commands) if (effect.type === 'complete') this.#options.onComplete?.(effect.value); this.#options.onUpdate?.(); } return result.ok; } handleKeyboardInput(input: TerminalKeyboardInput) { const event: PinInputEvent | null = input.key === 'left' ? 'previous' : input.key === 'right' ? 'next' : input.key === 'backspace' ? 'backspace' : input.key === 'delete' ? 'delete' : input.text !== undefined ? { type: 'input', value: input.text } : null; return event === null ? false : this.handleEvent(event); } }
