import { createFacadeConnection, type FacadeConnection } from './internal/facade.js';
import { unwrap } from '@sectile/core/result';
import type { Result } from '@sectile/core';
import type { RevisionSnapshot } from '@sectile/core/revision';
import { applyTagsInputEvent, createTagsInputState, type TagsInputCommand, type TagsInputEvent, type TagsInputPolicies, type TagsInputState } from '@sectile/core/tags-input';
import type { TerminalKeyboardInput } from './keyboard.js';
import { createSemanticController, type SemanticController } from './internal/semantic-controller.js';
export interface TagsInputOptions { readonly policies?: TagsInputPolicies; readonly disabled?: boolean; readonly readOnly?: boolean; readonly value?: readonly string[]; readonly defaultValue?: readonly string[]; readonly inputValue?: string; readonly defaultInputValue?: string; readonly onValueChange?: (value: readonly string[]) => void; readonly onInputValueChange?: (value: string) => void; readonly onUpdate?: () => void }
export interface TagsInputConnection { getSnapshot(): RevisionSnapshot<TagsInputState>; syncControlledValues(values: { readonly value?: readonly string[]; readonly inputValue?: string }): Result<RevisionSnapshot<TagsInputState>>; handleEvent(event: TagsInputEvent): boolean; handleKeyboardInput(input: TerminalKeyboardInput): boolean }
export function createTagsInput(options: TagsInputOptions = {}): FacadeConnection<TagsInputConnection> {
  return unwrap(tryCreateTagsInput(options));
}

export function tryCreateTagsInput(options: TagsInputOptions = {}): Result<FacadeConnection<TagsInputConnection>> {
  return createFacadeConnection(options, (options) => tryCreateTagsInputConnection(options));
}

function tryCreateTagsInputConnection(options: TagsInputOptions = {}): Result<TagsInputConnection> { const controlled = { value: options.value !== undefined, input: options.inputValue !== undefined }; const runtime = createSemanticController<TagsInputState, TagsInputEvent, TagsInputCommand, TagsInputCommand>({ interaction: options, interactionIntent: (event) => event === 'next' || event === 'previous' || event === 'focus-input' || (typeof event === 'object' && event.type === 'focus-tag') ? 'navigate' : 'mutate', initial: createTagsInputState(options.value ?? options.defaultValue ?? [], options.inputValue ?? options.defaultInputValue ?? ''), reducer: (state, event) => applyTagsInputEvent(state, event, options.policies), reconcile: (previous, proposed) => createTagsInputState(controlled.value ? previous.tags : proposed.tags, controlled.input ? previous.draft : proposed.draft, proposed.current), notify: (previous, proposed) => { if (previous.tags.join('\u0000') !== proposed.tags.join('\u0000')) options.onValueChange?.(proposed.tags); if (previous.draft !== proposed.draft) options.onInputValueChange?.(proposed.draft); }, toEffect: (command) => command }); return runtime.ok ? { ok: true, value: new TerminalTagsInputConnection(options, runtime.value, controlled) } : runtime; }
class TerminalTagsInputConnection implements TagsInputConnection { readonly #options: TagsInputOptions; readonly #runtime: SemanticController<TagsInputState, TagsInputEvent, TagsInputCommand>; readonly #controlled: { value: boolean; input: boolean }; constructor(options: TagsInputOptions, runtime: SemanticController<TagsInputState, TagsInputEvent, TagsInputCommand>, controlled: { value: boolean; input: boolean }) { this.#options = options; this.#runtime = runtime; this.#controlled = controlled; } getSnapshot() { return this.#runtime.getSnapshot(); } syncControlledValues(values: { readonly value?: readonly string[]; readonly inputValue?: string }) { if (this.#controlled.value !== (values.value !== undefined) || this.#controlled.input !== (values.inputValue !== undefined)) return { ok: false as const, error: { class: 'construction' as const, code: 'controlled-shape-mismatch', message: 'Controlled tags input values must preserve their construction-time shape.' } }; const state = this.#runtime.getSnapshot().state; const result = this.#runtime.replace(createTagsInputState(this.#controlled.value ? values.value ?? [] : state.tags, this.#controlled.input ? values.inputValue ?? '' : state.draft, state.current)); if (result.ok) this.#options.onUpdate?.(); return result; } handleEvent(event: TagsInputEvent) { const result = this.#runtime.handle(event); if (result.ok) this.#options.onUpdate?.(); return result.ok; } handleKeyboardInput(input: TerminalKeyboardInput) { const state = this.#runtime.getSnapshot().state; const event: TagsInputEvent | null = input.key === 'enter' || input.text === ',' ? { type: 'add' } : input.key === 'backspace' && state.draft.length === 0 ? (state.current === null ? 'previous' : 'remove-current') : input.key === 'left' ? 'previous' : input.key === 'right' ? 'next' : input.text !== undefined ? { type: 'input', value: `${state.draft}${input.text}` } : null; return event === null ? false : this.handleEvent(event); } }
