import { unwrap } from '@sectile/core/result';
import type { Result } from '@sectile/core';
import type { RevisionSnapshot } from '@sectile/core/revision';
import type { TextEditingState, TextEvent, TextSelectionInput } from '@sectile/core/text';
import { applyTimeRangeFieldEvent, tryCreateTimeRangeFieldState, type TimeRange, type TimeRangeFieldCommand, type TimeRangeFieldEndpoint, type TimeRangeFieldEvent, type TimeRangeFieldPolicies, type TimeRangeFieldState } from '@sectile/temporal/time-range-field';
import { createFacadeConnection, type FacadeConnection } from '@sectile/core/adapter-runtime';
import { createSemanticController, type SemanticController } from '@sectile/core/adapter-runtime';
import { toTerminalTextInput } from './internal/text-input.js';
import { toTextEvent } from './text.js';
import type { TerminalKeyboardInput } from './keyboard.js';

export interface TimeRangeFieldOptions { readonly value?: TimeRange | null; readonly defaultValue?: TimeRange | null; readonly startInputState?: TextEditingState; readonly defaultStartInputState?: TextEditingState; readonly endInputState?: TextEditingState; readonly defaultEndInputState?: TextEditingState; readonly policies?: TimeRangeFieldPolicies; readonly disabled?: boolean; readonly readOnly?: boolean; readonly required?: boolean; readonly onValueChange?: (value: TimeRange | null) => void; readonly onStartInputStateChange?: (value: TextEditingState) => void; readonly onEndInputStateChange?: (value: TextEditingState) => void; readonly onUpdate?: () => void }

export type TimeRangeFieldValueChangeHandler = NonNullable<TimeRangeFieldOptions['onValueChange']>;
export type TimeRangeFieldStartInputStateChangeHandler = NonNullable<TimeRangeFieldOptions['onStartInputStateChange']>;
export type TimeRangeFieldEndInputStateChangeHandler = NonNullable<TimeRangeFieldOptions['onEndInputStateChange']>;
export type TimeRangeFieldUpdateHandler = NonNullable<TimeRangeFieldOptions['onUpdate']>;
export interface TimeRangeFieldControlledValues { readonly value?: TimeRange | null; readonly startInputState?: TextEditingState; readonly endInputState?: TextEditingState }
export interface TimeRangeFieldConnection { getSnapshot(): RevisionSnapshot<TimeRangeFieldState>; getValue(): TimeRange | null; getText(endpoint: TimeRangeFieldEndpoint): string; syncControlledValues(values: TimeRangeFieldControlledValues): Result<RevisionSnapshot<TimeRangeFieldState>>; handleEvent(event: TimeRangeFieldEvent): boolean; handleKeyboardInput(input: TerminalKeyboardInput): boolean }
export function createTimeRangeField(options: TimeRangeFieldOptions = {}): FacadeConnection<TimeRangeFieldConnection> { return unwrap(tryCreateTimeRangeField(options)); }
export function tryCreateTimeRangeField(options: TimeRangeFieldOptions = {}): Result<FacadeConnection<TimeRangeFieldConnection>> { return createFacadeConnection(options, construct); }
function construct(options: TimeRangeFieldOptions): Result<TimeRangeFieldConnection> {
  const controlled = { value: options.value !== undefined, start: options.startInputState !== undefined, end: options.endInputState !== undefined };
  const runtime = createSemanticController<TimeRangeFieldState, TimeRangeFieldEvent, TimeRangeFieldCommand, TimeRangeFieldCommand>({ initial: tryCreateTimeRangeFieldState({ value: options.value !== undefined ? options.value : options.defaultValue ?? null, ...optionalInputState('startInputState', options.startInputState ?? options.defaultStartInputState), ...optionalInputState('endInputState', options.endInputState ?? options.defaultEndInputState) }), reducer: (state, event) => applyTimeRangeFieldEvent(state, event, { ...options.policies, ...(options.required === undefined ? {} : { required: options.required }) }), reconcile: (previous, proposed) => tryCreateTimeRangeFieldState({ startValue: controlled.value ? previous.start.value : proposed.start.value, endValue: controlled.value ? previous.end.value : proposed.end.value, startInputState: controlled.start ? previous.start.inputState : proposed.start.inputState, endInputState: controlled.end ? previous.end.inputState : proposed.end.inputState, active: proposed.active }), notify: (previous, proposed) => { if (previous.start.inputState !== proposed.start.inputState) options.onStartInputStateChange?.(proposed.start.inputState); if (previous.end.inputState !== proposed.end.inputState) options.onEndInputStateChange?.(proposed.end.inputState); }, toEffect: (command) => command, interaction: options });
  return runtime.ok ? { ok: true, value: new TerminalTimeRangeField(options, runtime.value, controlled) } : runtime;
}
class TerminalTimeRangeField implements TimeRangeFieldConnection {
  readonly options: TimeRangeFieldOptions; readonly runtime: SemanticController<TimeRangeFieldState, TimeRangeFieldEvent, TimeRangeFieldCommand>; readonly controlled: { readonly value: boolean; readonly start: boolean; readonly end: boolean };
  public constructor(options: TimeRangeFieldOptions, runtime: SemanticController<TimeRangeFieldState, TimeRangeFieldEvent, TimeRangeFieldCommand>, controlled: { readonly value: boolean; readonly start: boolean; readonly end: boolean }) { this.options = options; this.runtime = runtime; this.controlled = controlled; }
  public getSnapshot(): RevisionSnapshot<TimeRangeFieldState> { return this.runtime.getSnapshot(); } public getValue(): TimeRange | null { return this.getSnapshot().state.value; } public getText(endpoint: TimeRangeFieldEndpoint): string { return this.getSnapshot().state[endpoint].inputState.snapshot.text; }
  public syncControlledValues(values: TimeRangeFieldControlledValues): Result<RevisionSnapshot<TimeRangeFieldState>> { if (this.controlled.value !== (values.value !== undefined) || this.controlled.start !== (values.startInputState !== undefined) || this.controlled.end !== (values.endInputState !== undefined)) return { ok: false, error: { class: 'construction', code: 'controlled-shape-mismatch', message: 'Controlled time range field values must preserve their construction-time shape.' } }; const current = this.getSnapshot().state; const result = this.runtime.replace(tryCreateTimeRangeFieldState({ value: this.controlled.value ? values.value as TimeRange | null : current.value, ...optionalInputState('startInputState', this.controlled.start ? values.startInputState : current.start.inputState), ...optionalInputState('endInputState', this.controlled.end ? values.endInputState : current.end.inputState), active: current.active })); if (result.ok) this.options.onUpdate?.(); return result; }
  public handleEvent(event: TimeRangeFieldEvent): boolean { const result = this.runtime.handle(event); if (result.ok) { for (const command of result.commands) if (command.type === 'range-committed') this.options.onValueChange?.(command.value); this.options.onUpdate?.(); } return result.ok; }
  public handleKeyboardInput(input: TerminalKeyboardInput): boolean { const endpoint = this.getSnapshot().state.active; if (input.ctrlKey === true || input.altKey === true) return false; if (input.key === 'tab') return this.handleEvent({ type: 'focus', endpoint: endpoint === 'start' ? 'end' : 'start' }); if (input.key === 'enter') return this.handleEvent({ type: 'field', endpoint, event: 'commit' }); if (input.key === 'escape') return this.handleEvent('cancel'); if (input.key === 'up' || input.key === 'down') return this.handleEvent({ type: 'field', endpoint, event: input.key === 'up' ? 'increment-segment' : 'decrement-segment' }); if (input.key === 'left' || input.key === 'right' || input.key === 'home' || input.key === 'end') return this.#move(endpoint, input); const semantic = toTerminalTextInput(this.getSnapshot().state[endpoint].inputState, input); const event = semantic === null ? null : toTextEvent(semantic); return event !== null && this.handleEvent({ type: 'field', endpoint, event: { type: 'text', event } }); }
  #move(endpoint: TimeRangeFieldEndpoint, input: TerminalKeyboardInput): boolean { const snapshot = this.getSnapshot().state[endpoint].inputState.snapshot; const selection = snapshot.selection; const focus = input.key === 'home' ? 0 : input.key === 'end' ? snapshot.text.length : input.key === 'left' ? Math.max(0, selection.focusCodeUnitOffset - 1) : Math.min(snapshot.text.length, selection.focusCodeUnitOffset + 1); const next: TextSelectionInput = { anchorCodeUnitOffset: input.shiftKey === true ? selection.anchorCodeUnitOffset : focus, focusCodeUnitOffset: focus }; const event: TextEvent = { type: 'replace', startCodeUnitOffset: focus, endCodeUnitOffset: focus, text: '', selection: next }; return this.handleEvent({ type: 'field', endpoint, event: { type: 'text', event } }); }
}
function optionalInputState<Key extends 'startInputState' | 'endInputState'>(key: Key, value: TextEditingState | undefined): { readonly [Property in Key]?: TextEditingState } { return value === undefined ? {} : { [key]: value } as { readonly [Property in Key]?: TextEditingState }; }
