import { unwrap } from '@sectile/core/result';
import type { Result } from '@sectile/core';
import type { RevisionSnapshot } from '@sectile/core/revision';
import { sameTextEditingState, type TextEditingState, type TextEvent, type TextSelectionInput } from '@sectile/core/text';
import { applyTimeFieldEvent, tryCreateTimeFieldState, type TimeFieldCommand, type TimeFieldEvent, type TimeFieldPolicies, type TimeFieldState, type TimeValue } from '@sectile/temporal/time-field';
import { createFacadeConnection, type FacadeConnection } from '@sectile/core/adapter-runtime';
import { createSemanticController, type SemanticController } from '@sectile/core/adapter-runtime';
import { toTerminalTextInput } from './internal/text-input.js';
import type { TerminalKeyboardInput } from './keyboard.js';
import { toTextEvent } from './text.js';

export interface TimeFieldOptions { readonly policies?: TimeFieldPolicies; readonly value?: TimeValue | null; readonly defaultValue?: TimeValue | null; readonly inputState?: TextEditingState; readonly defaultInputState?: TextEditingState; readonly disabled?: boolean; readonly readOnly?: boolean; readonly required?: boolean; readonly onValueChange?: (value: TimeValue | null) => void; readonly onInputStateChange?: (value: TextEditingState, previousValue: TextEditingState) => void; readonly onUpdate?: () => void; }

export type TimeFieldValueChangeHandler = NonNullable<TimeFieldOptions['onValueChange']>;
export type TimeFieldInputStateChangeHandler = NonNullable<TimeFieldOptions['onInputStateChange']>;
export type TimeFieldUpdateHandler = NonNullable<TimeFieldOptions['onUpdate']>;
export interface TimeFieldControlledValues { readonly value?: TimeValue | null; readonly inputState?: TextEditingState; }
export interface TimeFieldConnection { getSnapshot(): RevisionSnapshot<TimeFieldState>; getText(): string; getValue(): TimeValue | null; getCaret(): number; syncControlledValues(values: TimeFieldControlledValues): Result<RevisionSnapshot<TimeFieldState>>; handleEvent(event: TimeFieldEvent): boolean; handleKeyboardInput(input: TerminalKeyboardInput): boolean; handleTextInput(text: string): boolean; }
export function createTimeField(options: TimeFieldOptions = {}): FacadeConnection<TimeFieldConnection> { return unwrap(tryCreateTimeField(options)); }
export function tryCreateTimeField(options: TimeFieldOptions = {}): Result<FacadeConnection<TimeFieldConnection>> { return createFacadeConnection(options, construct); }
function construct(options: TimeFieldOptions): Result<TimeFieldConnection> { const valueControlled = options.value !== undefined; const inputControlled = options.inputState !== undefined; const policies = Object.freeze({ ...options.policies, ...(options.required === undefined ? {} : { required: options.required }) }); const runtime = createSemanticController<TimeFieldState, TimeFieldEvent, TimeFieldCommand, TimeFieldCommand>({ initial: tryCreateTimeFieldState(options.value !== undefined ? options.value : options.defaultValue ?? null, options.inputState !== undefined ? options.inputState : options.defaultInputState), reducer: (state, event) => applyTimeFieldEvent(state, event, policies), reconcile: (previous, proposed) => tryCreateTimeFieldState(valueControlled ? previous.value : proposed.value, inputControlled ? previous.inputState : proposed.inputState), notify: (previous, proposed) => { if (!sameTextEditingState(previous.inputState, proposed.inputState)) options.onInputStateChange?.(proposed.inputState, previous.inputState); }, toEffect: (command) => command, interaction: options }); return runtime.ok ? { ok: true, value: new TerminalTimeField(options, runtime.value, valueControlled, inputControlled) } : runtime; }
class TerminalTimeField implements TimeFieldConnection {
  readonly options: TimeFieldOptions; readonly runtime: SemanticController<TimeFieldState, TimeFieldEvent, TimeFieldCommand>; readonly valueControlled: boolean; readonly inputControlled: boolean;
  public constructor(options: TimeFieldOptions, runtime: SemanticController<TimeFieldState, TimeFieldEvent, TimeFieldCommand>, valueControlled: boolean, inputControlled: boolean) { this.options = options; this.runtime = runtime; this.valueControlled = valueControlled; this.inputControlled = inputControlled; }
  public getSnapshot(): RevisionSnapshot<TimeFieldState> { return this.runtime.getSnapshot(); } public getText(): string { return this.getSnapshot().state.inputState.snapshot.text; } public getValue(): TimeValue | null { return this.getSnapshot().state.value; } public getCaret(): number { return this.getSnapshot().state.inputState.snapshot.selection.focusCodeUnitOffset; }
  public syncControlledValues(values: TimeFieldControlledValues): Result<RevisionSnapshot<TimeFieldState>> { if (this.valueControlled !== (values.value !== undefined) || this.inputControlled !== (values.inputState !== undefined)) return { ok: false, error: { class: 'construction', code: 'controlled-shape-mismatch', message: 'Controlled time field values must preserve their construction-time shape.' } }; const state = this.getSnapshot().state; const result = this.runtime.replace(tryCreateTimeFieldState(this.valueControlled ? values.value as TimeValue | null : state.value, this.inputControlled ? values.inputState as TextEditingState : state.inputState)); if (result.ok) this.options.onUpdate?.(); return result; }
  public handleEvent(event: TimeFieldEvent): boolean { const result = this.runtime.handle(event); if (result.ok) { for (const command of result.commands) if (command.type === 'value-committed') this.options.onValueChange?.(command.value); this.options.onUpdate?.(); } return result.ok; }
  public handleKeyboardInput(input: TerminalKeyboardInput): boolean { if (input.ctrlKey === true || input.altKey === true) return false; if (input.key === 'enter') return this.handleEvent('commit'); if (input.key === 'escape') return this.handleEvent('cancel'); if (input.key === 'up') return this.handleEvent('increment-segment'); if (input.key === 'down') return this.handleEvent('decrement-segment'); if (input.key === 'left' || input.key === 'right' || input.key === 'home' || input.key === 'end') return this.#move(input); const semantic = toTerminalTextInput(this.getSnapshot().state.inputState, input); const event = semantic === null ? null : toTextEvent(semantic); return event !== null && this.handleEvent({ type: 'text', event }); }
  public handleTextInput(text: string): boolean { return typeof text === 'string' && text.length > 0 && this.handleKeyboardInput({ key: text, text }); }
  #move(input: TerminalKeyboardInput): boolean { const snapshot = this.getSnapshot().state.inputState.snapshot; const selection = snapshot.selection; const focus = input.key === 'home' ? 0 : input.key === 'end' ? snapshot.text.length : input.key === 'left' ? Math.max(0, selection.focusCodeUnitOffset - 1) : Math.min(snapshot.text.length, selection.focusCodeUnitOffset + 1); const next: TextSelectionInput = { anchorCodeUnitOffset: input.shiftKey === true ? selection.anchorCodeUnitOffset : focus, focusCodeUnitOffset: focus }; const event: TextEvent = { type: 'replace', startCodeUnitOffset: focus, endCodeUnitOffset: focus, text: '', selection: next }; return this.handleEvent({ type: 'text', event }); }
}
