import type { QuantizedRange } from '../../../structures/range.js'; import type { SpinbuttonCommand, SpinbuttonEvent, SpinbuttonPolicies, SpinbuttonState } from '../../../spinbutton.js'; import { applyReferenceSliderEvent, createReferenceSliderState } from './slider.js';
export type ReferenceSpinbuttonResult={readonly ok:true;readonly value:{readonly state:SpinbuttonState;readonly commands:readonly SpinbuttonCommand[]}}|{readonly ok:false;readonly errorClass:string;readonly errorCode:string};
export function createReferenceSpinbuttonState(tick=0,draft:string|null=null):SpinbuttonState{return Object.freeze({tick,draft});}
export function applyReferenceSpinbuttonEvent(range:QuantizedRange,state:SpinbuttonState,event:SpinbuttonEvent,policies:SpinbuttonPolicies={}):ReferenceSpinbuttonResult {
  if(typeof event==='object'&&event.type==='input')return accepted(createReferenceSpinbuttonState(state.tick,event.text),event.text===state.draft?[]:[{type:'draft-changed',text:event.text}]);
  if(event==='cancel')return accepted(createReferenceSpinbuttonState(state.tick,null),state.draft===null?[]:[{type:'draft-changed',text:null}]);
  if(event==='commit'){if(state.draft===null)return accepted(state,[]);const parsed=(policies.parse??((text:string)=>text))(state.draft);const tick=parsed===null?null:range.tickOf(parsed);if(tick===null)return rejected('spinbutton-draft-invalid');return accepted(createReferenceSpinbuttonState(tick,null),[{type:'draft-changed',text:null},...(tick===state.tick?[]:[{type:'announce-tick' as const,tick}])]);}
  const moved=applyReferenceSliderEvent(range,createReferenceSliderState(range,state.tick),event,policies.page);if(!moved.ok)return{ok:false,errorClass:moved.errorClass,errorCode:moved.errorCode};return accepted(createReferenceSpinbuttonState(moved.value.state.tick,null),[...(state.draft===null?[]:[{type:'draft-changed' as const,text:null}]),...moved.value.commands]);
}
function accepted(state:SpinbuttonState,commands:readonly SpinbuttonCommand[]):ReferenceSpinbuttonResult{return{ok:true,value:{state,commands}}} function rejected(errorCode:string):ReferenceSpinbuttonResult{return{ok:false,errorClass:'transition-rejection',errorCode}}
