import type { QuantizedRange } from '../../../structures/range.js'; import type { SpinButtonCommand, SpinButtonEvent, SpinButtonPolicies, SpinButtonState } from '../../../spin-button.js'; import { applyReferenceSliderEvent, createReferenceSliderState } from './slider.js';
export type ReferenceSpinButtonResult={readonly ok:true;readonly value:{readonly state:SpinButtonState;readonly commands:readonly SpinButtonCommand[]}}|{readonly ok:false;readonly errorClass:string;readonly errorCode:string};
export function createReferenceSpinButtonState(tick=0,draft:string|null=null):SpinButtonState{return Object.freeze({tick,draft});}
export function applyReferenceSpinButtonEvent(range:QuantizedRange,state:SpinButtonState,event:SpinButtonEvent,policies:SpinButtonPolicies={}):ReferenceSpinButtonResult {
  if(typeof event==='object'&&event.type==='input')return accepted(createReferenceSpinButtonState(state.tick,event.text),event.text===state.draft?[]:[{type:'draft-changed',text:event.text}]);
  if(event==='cancel')return accepted(createReferenceSpinButtonState(state.tick,null),state.draft===null?[]:[{type:'draft-changed',text:null}]);
  if(event==='commit'){if(state.draft===null)return accepted(state,[]);const parsed=(policies.parse??((text:string)=>text))(state.draft);const tick=parsed===null?null:range.tickOf(parsed);if(tick===null)return rejected('spin-button-draft-invalid');return accepted(createReferenceSpinButtonState(tick,null),[{type:'draft-changed',text:null},...(tick===state.tick?[]:[{type:'announce-tick' as const,tick}])]);}
  const moved=applyReferenceSliderEvent(range,createReferenceSliderState(range,state.tick),event,policies.page);if(!moved.ok)return{ok:false,errorClass:moved.errorClass,errorCode:moved.errorCode};return accepted(createReferenceSpinButtonState(moved.value.state.tick,null),[...(state.draft===null?[]:[{type:'draft-changed' as const,text:null}]),...moved.value.commands]);
}
function accepted(state:SpinButtonState,commands:readonly SpinButtonCommand[]):ReferenceSpinButtonResult{return{ok:true,value:{state,commands}}} function rejected(errorCode:string):ReferenceSpinButtonResult{return{ok:false,errorClass:'transition-rejection',errorCode}}
