import { unwrap } from './result.js';
import type { Result, StableID } from './shared.js'; import type { Sequence } from './structures/sequence.js'; import { fail, ok } from './internal/kernel/foundation.js'; import { createMachineUpdate } from './internal/kernel/machine.js'; import { createCursorState, type CursorState } from './internal/state/cursor.js';
export type FeedDirection = 'before' | 'after'; export interface FeedState<ID extends StableID = StableID> { readonly cursor: CursorState<ID>; readonly revision: number; readonly pending: FeedDirection | null } export type FeedEvent<ID extends StableID = StableID> = 'next' | 'previous' | 'request-before' | 'request-after' | 'clear-request' | { readonly type: 'focus'; readonly id: ID }; export type FeedCommand<ID extends StableID = StableID> = { readonly type: 'focus'; readonly id: ID } | { readonly type: 'request-window'; readonly direction: FeedDirection; readonly anchor: ID | null; readonly revision: number }; export interface FeedUpdate<ID extends StableID = StableID> { readonly state: FeedState<ID>; readonly commands: readonly FeedCommand<ID>[] }
export function createFeedState<ID extends StableID>(items: Sequence<ID>, current: ID | null = null, revision = 0, pending: FeedDirection | null = null): FeedState<ID> {
  return unwrap(tryCreateFeedState(items, current, revision, pending));
}

export function tryCreateFeedState<ID extends StableID>(items: Sequence<ID>, current: ID | null = null, revision = 0, pending: FeedDirection | null = null): Result<FeedState<ID>> { if (current !== null && !items.contains(current)) return fail('construction', 'feed-cursor-outside-window', 'Feed cursor must identify an item in the current window.'); if (!Number.isSafeInteger(revision) || revision < 0) return fail('construction', 'invalid-feed-revision', 'Feed revision must be a non-negative safe integer.'); if (pending !== null && pending !== 'before' && pending !== 'after') return fail('construction', 'invalid-feed-pending-direction', 'Feed pending direction must be before or after.'); return ok(Object.freeze({ cursor: createCursorState(current), revision, pending })); }
export function applyFeedEvent<ID extends StableID>(items: Sequence<ID>, state: FeedState<ID>, event: FeedEvent<ID>): Result<FeedUpdate<ID>> { const valid = tryCreateFeedState(items, state.cursor.current, state.revision, state.pending); if (!valid.ok) return { ok: false, error: { ...valid.error, class: 'transition-rejection' } }; if (event === 'clear-request') return createMachineUpdate(Object.freeze({ ...state, pending: null })); if (event === 'request-before' || event === 'request-after') { if (state.pending !== null) return createMachineUpdate(state); const direction = event === 'request-before' ? 'before' : 'after'; return createMachineUpdate(Object.freeze({ ...state, pending: direction }), [{ type: 'request-window', direction, anchor: state.cursor.current, revision: state.revision }]); } let id: ID | null; if (typeof event === 'object') { if (!items.contains(event.id)) return fail('transition-rejection', 'feed-target-unavailable', 'Direct feed focus requires an item in the current window.'); id = event.id; } else if (state.cursor.current === null) id = items.at(event === 'next' ? 0 : items.size - 1); else { const moved = items.move(state.cursor.current, event === 'next' ? 1 : -1, 'stop'); id = moved.kind === 'found' ? moved.id : state.cursor.current; } return id === null || id === state.cursor.current ? createMachineUpdate(state) : createMachineUpdate(Object.freeze({ ...state, cursor: createCursorState(id) }), [{ type: 'focus', id }]); }
