import type { Result } from './shared.js'; import type { QuantizedRange } from './structures/range.js'; import { fail, ok } from './internal/kernel/foundation.js'; import { createMachineUpdate } from './internal/kernel/machine.js'; import { applySliderEvent, createSliderState, type SliderEvent } from './internal/composites/slider.js';
export interface SpinbuttonState { readonly tick: number; readonly draft: string | null }
export type SpinbuttonEvent = SliderEvent | { readonly type: 'input'; readonly text: string } | 'commit' | 'cancel';
export type SpinbuttonCommand = { readonly type: 'draft-changed'; readonly text: string | null } | { readonly type: 'announce-tick'; readonly tick: number };
export interface SpinbuttonPolicies { readonly page?: number; readonly parse?: (text: string) => string | null }
export interface SpinbuttonUpdate { readonly state: SpinbuttonState; readonly commands: readonly SpinbuttonCommand[] }
export function createSpinbuttonState(range: QuantizedRange, tick = 0, draft: string | null = null): Result<SpinbuttonState> { const base = createSliderState(range, tick); if (!base.ok) return base; if (draft !== null && typeof draft !== 'string') return fail('construction','invalid-spinbutton-draft','Spinbutton draft must be text or null.'); return ok(Object.freeze({ tick, draft })); }
export function applySpinbuttonEvent(range: QuantizedRange, state: SpinbuttonState, event: SpinbuttonEvent, policies: SpinbuttonPolicies = {}): Result<SpinbuttonUpdate> {
  const valid = createSpinbuttonState(range,state.tick,state.draft); if (!valid.ok) return {ok:false,error:{...valid.error,class:'transition-rejection'}};
  if (typeof event === 'object' && event.type === 'input') { if (typeof event.text !== 'string') return fail('transition-rejection','invalid-spinbutton-input','Spinbutton input must be text.'); if (event.text===state.draft) return createMachineUpdate(state); return createMachineUpdate(Object.freeze({tick:state.tick,draft:event.text}),[{type:'draft-changed',text:event.text}]); }
  if (event === 'cancel') { if (state.draft===null) return createMachineUpdate(state); return createMachineUpdate(Object.freeze({tick:state.tick,draft:null}),[{type:'draft-changed',text:null}]); }
  if (event === 'commit') { if (state.draft===null) return createMachineUpdate(state); const parsed=(policies.parse??((text:string)=>text))(state.draft); const tick=parsed===null?null:range.tickOf(parsed); if (tick===null) return fail('transition-rejection','spinbutton-draft-invalid','Spinbutton draft must parse to a value on the range lattice.',{draft:state.draft}); const commands:SpinbuttonCommand[]=[{type:'draft-changed',text:null}]; if(tick!==state.tick)commands.push({type:'announce-tick',tick}); return createMachineUpdate(Object.freeze({tick,draft:null}),commands); }
  const moved=applySliderEvent(range,{tick:state.tick},event,policies.page); if(!moved.ok)return moved; const commands:SpinbuttonCommand[]=[]; if(state.draft!==null)commands.push({type:'draft-changed',text:null}); commands.push(...moved.value.commands); return createMachineUpdate(Object.freeze({tick:moved.value.state.tick,draft:null}),commands);
}
