import { computed, defineComponent, h, inject, mergeProps, nextTick, onBeforeUnmount, onMounted, provide, ref, shallowRef, watch, type ComputedRef, type PropType, type SlotsType, type VNodeChild } from 'vue';
import { createTimeRangeField, tryCreateTimeRangeFieldState, type TimeRange, type TimeRangeFieldConnection, type TimeRangeFieldPolicies, type TimeRangeFieldState } from '@sectile/dom/time-range-field';
import { Primitive, type PrimitiveAs } from './primitive.js';

export interface TimeRangeFieldRootProps { readonly modelValue?: TimeRange | null; readonly defaultValue?: TimeRange | null; readonly policies?: TimeRangeFieldPolicies; readonly disabled?: boolean; readonly?: boolean; readonly required?: boolean; readonly startLabel?: string; readonly endLabel?: string; readonly as?: PrimitiveAs; readonly asChild?: boolean }
export interface TimeRangeFieldRootSlotProps { readonly value: TimeRange | null; readonly startText: string; readonly endText: string; readonly active: 'start' | 'end'; readonly disabled: boolean; readonly: boolean }
interface Context { readonly slotProps: ComputedRef<TimeRangeFieldRootSlotProps>; readonly startInput: ReturnType<typeof ref<HTMLInputElement | null>>; readonly endInput: ReturnType<typeof ref<HTMLInputElement | null>> }
const contextKey = Symbol('SectileTimeRangeField');

export const TimeRangeFieldRoot = defineComponent({
  name: 'SectileTimeRangeFieldRoot', inheritAttrs: false,
  props: { modelValue: { type: Object as PropType<TimeRange | null>, default: undefined }, defaultValue: { type: Object as PropType<TimeRange | null>, default: null }, policies: { type: Object as PropType<TimeRangeFieldPolicies>, default: undefined }, disabled: { type: Boolean, default: false }, readonly: { type: Boolean, default: false }, required: { type: Boolean, default: false }, startLabel: { type: String, default: undefined }, endLabel: { type: String, default: undefined }, as: { type: [String, Object, Function] as PropType<PrimitiveAs>, default: 'div' }, asChild: { type: Boolean, default: false } },
  emits: { 'update:modelValue': (_value: TimeRange | null): boolean => true }, slots: Object as SlotsType<{ default: (props: TimeRangeFieldRootSlotProps) => VNodeChild }>,
  setup(props, { attrs, emit, slots }) {
    const controlled = props.modelValue !== undefined; const initial = tryCreateTimeRangeFieldState({ value: controlled ? props.modelValue as TimeRange | null : props.defaultValue }); if (!initial.ok) throw new TypeError(initial.error.message);
    const snapshot = shallowRef<TimeRangeFieldState>(initial.value); const startInput = ref<HTMLInputElement | null>(null); const endInput = ref<HTMLInputElement | null>(null); let connection: TimeRangeFieldConnection | null = null;
    const refresh = (): void => { if (connection !== null) snapshot.value = connection.getSnapshot().state; };
    const mount = (): void => { if (startInput.value === null || endInput.value === null) return; connection?.disconnect(); connection = createTimeRangeField({ startInput: startInput.value, endInput: endInput.value, ...(controlled ? { value: props.modelValue as TimeRange | null } : { defaultValue: snapshot.value.value }), ...(props.policies === undefined ? {} : { policies: props.policies }), disabled: props.disabled, readOnly: props.readonly, required: props.required, ...(props.startLabel === undefined ? {} : { startLabel: props.startLabel }), ...(props.endLabel === undefined ? {} : { endLabel: props.endLabel }), onValueChange: (value) => emit('update:modelValue', value), onUpdate: refresh }); refresh(); };
    onMounted(mount); onBeforeUnmount(() => connection?.disconnect());
    watch(() => props.modelValue, (value) => { if (!controlled || value === undefined || connection === null) return; const result = connection.syncControlledValues({ value }); if (!result.ok) throw new TypeError(result.error.message); snapshot.value = result.value.state; });
    watch([() => props.policies, () => props.disabled, () => props.readonly, () => props.required, () => props.startLabel, () => props.endLabel], () => { void nextTick(mount); });
    const slotProps = computed<TimeRangeFieldRootSlotProps>(() => Object.freeze({ value: snapshot.value.value, startText: snapshot.value.start.inputState.snapshot.text, endText: snapshot.value.end.inputState.snapshot.text, active: snapshot.value.active, disabled: props.disabled, readonly: props.readonly })); provide<Context>(contextKey, { slotProps, startInput, endInput });
    return (): VNodeChild => h(Primitive, mergeProps(attrs, { as: props.as, asChild: props.asChild, 'data-scope': 'time-range-field', 'data-part': 'root', 'data-disabled': props.disabled ? '' : undefined, 'data-readonly': props.readonly ? '' : undefined }), { default: () => slots['default']?.(slotProps.value) });
  },
});
export const TimeRangeFieldStartInput = createEndpointInput('start', 'SectileTimeRangeFieldStartInput');
export const TimeRangeFieldEndInput = createEndpointInput('end', 'SectileTimeRangeFieldEndInput');
function createEndpointInput(endpoint: 'start' | 'end', name: string) { return defineComponent({ name, inheritAttrs: false, setup(_props, { attrs }) { const context = useContext(name); return (): VNodeChild => h('input', mergeProps(attrs, { ref: (element: unknown) => { context[endpoint === 'start' ? 'startInput' : 'endInput'].value = element as HTMLInputElement | null; }, type: 'text', inputmode: 'numeric', placeholder: 'HH:mm', value: endpoint === 'start' ? context.slotProps.value.startText : context.slotProps.value.endText, disabled: context.slotProps.value.disabled, readonly: context.slotProps.value.readonly, 'aria-disabled': String(context.slotProps.value.disabled), 'aria-readonly': String(context.slotProps.value.readonly), 'data-scope': 'time-range-field', 'data-part': `${endpoint}-input`, 'data-active': context.slotProps.value.active === endpoint ? '' : undefined })); } }); }
function useContext(part: string): Context { const context = inject<Context>(contextKey); if (context === undefined) throw new TypeError(`${part} must be used inside TimeRangeFieldRoot.`); return context; }
export type { TimeRange };
