import { unwrap } from '@sectile/core/result';
import { createDOMTemporalController, createDOMTemporalFacadeConnection, type DOMTemporalController, type DOMTemporalResult } from './internal/result.js';
import type { RevisionSnapshot } from '@sectile/core/revision';
import { compareDateValues, dateRangeContains, formatDateValue, type DateRange, type DateValue } from '@sectile/temporal/date-field';
import { calendarID, createCalendarMonth, createCalendarWeek, createCalendarYear, isCalendarValueAvailable, type CalendarMonthValue } from '@sectile/temporal/calendar';
import type { DatePickerEvent, DatePickerPolicies } from '@sectile/temporal/date-picker';
import { applyDateRangePickerEvent, tryCreateDateRangePickerState, type DateRangePickerCommand, type DateRangePickerEvent, type DateRangePickerState } from '@sectile/temporal/date-range-picker';
export type { DatePickerPolicies } from '@sectile/temporal/date-picker';
import { type FacadeConnection } from '@sectile/core/adapter-runtime';
import { setInteractionAttributes } from './internal/interaction.js';
import { setDatePickerCellAvailability } from './internal/date-picker-cell.js';
import { createDOMLayerBinding, type DOMLayerBinding } from './internal/layer-binding.js';
import { currentReferenceDate } from './internal/reference-date.js';
import { createPickerPosition, type PickerPositionOptions } from './internal/picker-position.js';
import type { FloatingPositionConnection } from './internal/floating-position.js';

export interface DateRangePickerOptions extends PickerPositionOptions { readonly root: HTMLElement; readonly grid: HTMLElement; readonly trigger: HTMLElement; readonly startInput?: HTMLInputElement; readonly endInput?: HTMLInputElement; readonly policies?: DatePickerPolicies; readonly value?: DateRange | null; readonly defaultValue?: DateRange | null; readonly highlightedValue?: DateValue; readonly defaultHighlightedValue?: DateValue; readonly referenceDate?: DateValue; readonly open?: boolean; readonly defaultOpen?: boolean; readonly disabled?: boolean; readonly readOnly?: boolean; readonly required?: boolean; readonly label?: string; readonly onValueChange?: (value: DateRange | null) => void; readonly onHighlightedValueChange?: (value: DateValue) => void; readonly onOpenChange?: (open: boolean) => void; readonly onUpdate?: () => void; }

export type DateRangePickerValueChangeHandler = NonNullable<DateRangePickerOptions['onValueChange']>;
export type DateRangePickerHighlightedValueChangeHandler = NonNullable<DateRangePickerOptions['onHighlightedValueChange']>;
export type DateRangePickerOpenChangeHandler = NonNullable<DateRangePickerOptions['onOpenChange']>;
export type DateRangePickerUpdateHandler = NonNullable<DateRangePickerOptions['onUpdate']>;
export interface DateRangePickerControlledValues { readonly value?: DateRange | null; readonly highlightedValue?: DateValue; readonly open?: boolean; }
export interface DateRangePickerConnection { getSnapshot(): RevisionSnapshot<DateRangePickerState>; getMonth(): readonly (readonly DateValue[])[]; getWeek(): readonly DateValue[]; getYear(): readonly (readonly CalendarMonthValue[])[]; syncControlledValues(values: DateRangePickerControlledValues): DOMTemporalResult<RevisionSnapshot<DateRangePickerState>>; setCellAttributes(element: HTMLElement, value: DateValue): void; handleEvent(event: DateRangePickerEvent): boolean; refresh(): void; disconnect(): void; }
export function createDateRangePicker(options: DateRangePickerOptions): FacadeConnection<DateRangePickerConnection> { return unwrap(tryCreateDateRangePicker(options)); }
export function tryCreateDateRangePicker(options: DateRangePickerOptions): DOMTemporalResult<FacadeConnection<DateRangePickerConnection>> { return createDOMTemporalFacadeConnection(options, construct); }
function construct(options: DateRangePickerOptions): DOMTemporalResult<DateRangePickerConnection> { const controls = { value: options.value !== undefined, highlighted: options.highlightedValue !== undefined, open: options.open !== undefined }; const requestedValue = controls.value ? options.value : options.defaultValue; const requestedHighlight = controls.highlighted ? options.highlightedValue : options.defaultHighlightedValue; const requestedOpen = controls.open ? options.open : options.defaultOpen; const initial = tryCreateDateRangePickerState({ referenceDate: options.referenceDate ?? currentReferenceDate(), ...(requestedValue === undefined ? {} : { value: requestedValue }), calendar: { ...(requestedHighlight === undefined ? {} : { highlighted: requestedHighlight }), ...(requestedOpen === undefined ? {} : { open: requestedOpen }) } }); const runtime = createDOMTemporalController<DateRangePickerState, DateRangePickerEvent, DateRangePickerCommand, DateRangePickerCommand>({ initial, reducer: (state, event) => applyDateRangePickerEvent(state, event, { ...options.policies, ...(options.required === undefined ? {} : { required: options.required }) }), reconcile: (previous, proposed) => tryCreateDateRangePickerState({ value: controls.value ? previous.value : proposed.value, anchor: proposed.anchor, calendar: { ...proposed.calendar, highlighted: controls.highlighted ? previous.calendar.highlighted : proposed.calendar.highlighted, view: controls.highlighted ? previous.calendar.view : proposed.calendar.view, open: controls.open ? previous.calendar.open : proposed.calendar.open } }), notify: (previous, proposed) => { if (rangeKey(previous.value) !== rangeKey(proposed.value)) options.onValueChange?.(proposed.value); if (compareDateValues(previous.calendar.highlighted, proposed.calendar.highlighted) !== 0) options.onHighlightedValueChange?.(proposed.calendar.highlighted); if (previous.calendar.open !== proposed.calendar.open) options.onOpenChange?.(proposed.calendar.open); }, toEffect: (command) => command, interaction: options }); return runtime.ok ? { ok: true, value: new DOMDateRangePicker(options, runtime.value, controls) } : runtime; }
class DOMDateRangePicker implements DateRangePickerConnection {
  readonly options: DateRangePickerOptions; readonly runtime: DOMTemporalController<DateRangePickerState, DateRangePickerEvent, DateRangePickerCommand>; readonly controls: { value: boolean; highlighted: boolean; open: boolean };
  readonly #layer: DOMLayerBinding;
  readonly #position: FloatingPositionConnection;
  readonly #trigger = (): void => { this.handleEvent('toggle'); }; readonly #keydown = (event: KeyboardEvent): void => { const semantic = keyEvent(event); if (semantic !== null) { event.preventDefault(); this.handleEvent(semantic); } }; readonly #click = (event: MouseEvent): void => { const target = event.target instanceof Element ? event.target.closest<HTMLElement>('[data-date-picker-id]') : null; const parts = target?.dataset['datePickerId']?.split('-').map(Number); if (target !== null && this.options.grid.contains(target) && parts?.length === 3) this.handleEvent({ type: 'select', value: { year: parts[0] as number, month: parts[1] as number, day: parts[2] as number } }); };
  public constructor(options: DateRangePickerOptions, runtime: DOMTemporalController<DateRangePickerState, DateRangePickerEvent, DateRangePickerCommand>, controls: { value: boolean; highlighted: boolean; open: boolean }) { this.options = options; this.runtime = runtime; this.controls = controls; this.#layer = createDOMLayerBinding({ surface: options.root, owner: options.trigger, dismissOnInteractOutside: true, readOpen: () => this.getSnapshot().state.calendar.open, close: () => { this.handleEvent('close'); } }); this.#position = createPickerPosition(options.root, options.trigger, options); options.trigger.addEventListener('click', this.#trigger); options.grid.addEventListener('keydown', this.#keydown); options.grid.addEventListener('click', this.#click); options.root.setAttribute('role', 'dialog'); options.grid.setAttribute('role', 'grid'); setInteractionAttributes(options.trigger, options, { native: true }); setInteractionAttributes(options.grid, options); this.refresh(); }
  public getSnapshot(): RevisionSnapshot<DateRangePickerState> { return this.runtime.getSnapshot(); } public getMonth(): readonly (readonly DateValue[])[] { const state = this.getSnapshot().state.calendar; return createCalendarMonth(state.view, this.options.policies?.weekStartsOn); } public getWeek(): readonly DateValue[] { const state = this.getSnapshot().state.calendar; return createCalendarWeek(state.highlighted, this.options.policies?.weekStartsOn); } public getYear(): readonly (readonly CalendarMonthValue[])[] { return createCalendarYear(this.getSnapshot().state.calendar.view.year); }
  public syncControlledValues(values: DateRangePickerControlledValues): DOMTemporalResult<RevisionSnapshot<DateRangePickerState>> { if (this.controls.value !== (values.value !== undefined) || this.controls.highlighted !== (values.highlightedValue !== undefined) || this.controls.open !== (values.open !== undefined)) return { ok: false, error: { class: 'construction', code: 'controlled-shape-mismatch', message: 'Controlled date range picker values must preserve their construction-time shape.' } }; const state = this.getSnapshot().state; const highlighted = this.controls.highlighted ? values.highlightedValue as DateValue : state.calendar.highlighted; const result = this.runtime.replace(tryCreateDateRangePickerState({ value: this.controls.value ? values.value as DateRange | null : state.value, anchor: state.anchor, calendar: { highlighted, view: { year: highlighted.year, month: highlighted.month }, viewMode: state.calendar.viewMode, open: this.controls.open ? values.open as boolean : state.calendar.open } })); if (result.ok) { this.refresh(); this.options.onUpdate?.(); } return result; }
  public setCellAttributes(element: HTMLElement, value: DateValue): void { const state = this.getSnapshot().state; element.dataset['datePickerId'] = calendarID(value); element.setAttribute('role', 'gridcell'); element.setAttribute('aria-selected', String((state.value !== null && dateRangeContains(state.value, value)) || (state.anchor !== null && compareDateValues(state.anchor, value) === 0))); setDatePickerCellAvailability(element, isCalendarValueAvailable(value, this.options.policies)); element.tabIndex = compareDateValues(state.calendar.highlighted, value) === 0 ? 0 : -1; }
  public handleEvent(event: DateRangePickerEvent): boolean { const result = this.runtime.handle(event); if (result.ok) { this.refresh(); this.options.onUpdate?.(); if (result.commands.some((command) => command.type === 'open-changed' && !command.open)) this.options.trigger.focus(); else if (result.commands.some((command) => command.type === 'highlight-changed')) queueMicrotask(() => this.options.grid.querySelector<HTMLElement>('[tabindex="0"]')?.focus()); } return result.ok; }
  public refresh(): void { const state = this.getSnapshot().state; this.options.root.hidden = !state.calendar.open; this.options.trigger.setAttribute('aria-haspopup', 'dialog'); this.options.trigger.setAttribute('aria-expanded', String(state.calendar.open)); if (this.options.label !== undefined) this.options.grid.setAttribute('aria-label', this.options.label); for (const [input, value] of [[this.options.startInput, state.value?.start], [this.options.endInput, state.value?.end]] as const) if (input !== undefined) { input.value = value === undefined ? '' : formatDateValue(value); input.readOnly = true; setInteractionAttributes(input, this.options, { native: true, readOnly: true }); } this.#layer.sync(); this.#position.update(); }
  public disconnect(): void { this.#layer.disconnect(); this.#position.disconnect(); this.options.trigger.removeEventListener('click', this.#trigger); this.options.grid.removeEventListener('keydown', this.#keydown); this.options.grid.removeEventListener('click', this.#click); }
}
function keyEvent(event: KeyboardEvent): DatePickerEvent | null { if (event.altKey || event.ctrlKey || event.metaKey) return null; if (event.key === 'ArrowLeft') return 'previous-day'; if (event.key === 'ArrowRight') return 'next-day'; if (event.key === 'ArrowUp') return 'previous-week'; if (event.key === 'ArrowDown') return 'next-week'; if (event.key === 'Home') return 'start-of-week'; if (event.key === 'End') return 'end-of-week'; if (event.key === 'PageUp') return event.shiftKey ? 'previous-year' : 'previous-month'; if (event.key === 'PageDown') return event.shiftKey ? 'next-year' : 'next-month'; if (event.key === 'Enter' || event.key === ' ') return 'select-highlighted'; if (event.key === 'Escape') return 'close'; return null; }
function rangeKey(value: DateRange | null): string { return value === null ? '' : `${formatDateValue(value.start)}/${formatDateValue(value.end)}`; }
