import type { Result, StableID } from '@sectile/primitives';
import type { RatingEvent, RatingState } from '@sectile/primitives/rating';
import type { RevisionSnapshot } from '@sectile/primitives/revision';
import { createRadioGroup, type RadioGroupConnection, type RadioGroupOptions } from './radio-group.js';

export type RatingOptions<ID extends StableID = StableID> = Omit<RadioGroupOptions<ID>, 'orientation' | 'onValueChange'> & { readonly clearable?: boolean; readonly onValueChange?: (value: ID | null) => void };
export interface RatingConnection<ID extends StableID = StableID> { getSnapshot(): RevisionSnapshot<RatingState<ID>>; syncControlledValues(values: { readonly value?: ID | null; readonly highlightedValue?: ID | null }): Result<RevisionSnapshot<RatingState<ID>>>; setItemAttributes(element: HTMLElement, id: ID, disabled?: boolean): void; handleEvent(event: RatingEvent<ID>): boolean; disconnect(): void }
export function createRating<ID extends StableID>(options: RatingOptions<ID>): Result<RatingConnection<ID>> {
  const uncontrolled = options.value === undefined; let value = options.value ?? options.defaultValue ?? null; let highlightedValue = options.highlightedValue ?? options.defaultHighlightedValue ?? value; let base: RadioGroupConnection<ID>;
  const result = createRadioGroup({ ...options, orientation: 'horizontal', value, highlightedValue, onValueChange: (next) => { options.onValueChange?.(next); if (uncontrolled) { value = next; queueMicrotask(sync); } }, onHighlightedValueChange: (next) => { highlightedValue = next; queueMicrotask(sync); } });
  if (!result.ok) return result; base = result.value;
  function sync(): void { base.syncControlledValues({ value, highlightedValue }); }
  return { ok: true, value: Object.freeze({ getSnapshot: () => base.getSnapshot(), syncControlledValues: (values: { readonly value?: ID | null; readonly highlightedValue?: ID | null }) => { if (values.value !== undefined) value = values.value; if (values.highlightedValue !== undefined) highlightedValue = values.highlightedValue; return base.syncControlledValues({ value, highlightedValue }); }, setItemAttributes: (element: HTMLElement, id: ID, disabled?: boolean) => { base.setItemAttributes(element, id, disabled); element.setAttribute('aria-label', `${id} rating`); }, handleEvent: (event: RatingEvent<ID>) => { if (event === 'clear') { if (options.clearable !== true) return false; options.onValueChange?.(null); if (uncontrolled) { value = null; return base.syncControlledValues({ value, highlightedValue }).ok; } return true; } return base.handleEvent(mapEvent(event)); }, disconnect: () => base.disconnect() }) };
}
function mapEvent<ID extends StableID>(event: Exclude<RatingEvent<ID>, 'clear'>) { if (typeof event === 'object') return event.type === 'set' ? { type: 'check' as const, id: event.id } : event; return event === 'increase' ? 'next' as const : event === 'decrease' ? 'previous' as const : event === 'minimum' ? 'first' as const : event === 'maximum' ? 'last' as const : 'check' as const; }
