import type { Result } from '@sectile/core';
import { applyTimerEvent, createTimerState, getTimerParts, getTimerProgress, type TimerCommand, type TimerEvent, type TimerParts, type TimerPolicies, type TimerState } from '@sectile/core/timer';
import type { RevisionSnapshot } from '@sectile/core/revision';
import { unwrap } from '@sectile/core/result';
import { createFacadeConnection, type FacadeConnection } from './internal/facade.js';
import { createSemanticController, type SemanticController } from './internal/semantic-controller.js';

export type TimerItemType = keyof TimerParts;
export type TimerAction = 'start' | 'pause' | 'resume' | 'reset' | 'restart' | 'toggle';
export interface TimerOptions extends TimerPolicies { readonly root: HTMLElement; readonly autoStart?: boolean; readonly intervalMs?: number; readonly onTick?: (valueMs: number, parts: TimerParts) => void; readonly onComplete?: (valueMs: number) => void; readonly onUpdate?: () => void }
export interface TimerConnection { getSnapshot(): RevisionSnapshot<TimerState>; handleEvent(event: TimerEvent): boolean; start(): boolean; pause(): boolean; resume(): boolean; reset(): boolean; restart(): boolean; setItemAttributes(element: HTMLElement, type: TimerItemType): void; setActionAttributes(element: HTMLButtonElement, action: TimerAction): void; disconnect(): void }
export function createTimer(options: TimerOptions): FacadeConnection<TimerConnection> { return unwrap(tryCreateTimer(options)); }
export function tryCreateTimer(options: TimerOptions): Result<FacadeConnection<TimerConnection>> { return createFacadeConnection(options, (normalized) => tryCreateTimerConnection(normalized)); }
function tryCreateTimerConnection(options: TimerOptions): Result<TimerConnection> { const policies: TimerPolicies = { ...(options.countdown === undefined ? {} : { countdown: options.countdown }), ...(options.startMs === undefined ? {} : { startMs: options.startMs }), ...(options.targetMs === undefined ? {} : { targetMs: options.targetMs }) }; const runtime = createSemanticController<TimerState, TimerEvent, TimerCommand, TimerCommand>({ initial: createTimerState(policies, policies.startMs ?? 0, options.autoStart ?? false), reducer: (state, event) => applyTimerEvent(state, event, policies), toEffect: (command) => command }); return runtime.ok ? { ok: true, value: new DOMTimer(options, policies, runtime.value) } : runtime; }

class DOMTimer implements TimerConnection {
  readonly #options: TimerOptions; readonly #policies: TimerPolicies; readonly #runtime: SemanticController<TimerState, TimerEvent, TimerCommand>;
  readonly #items = new Map<TimerItemType, HTMLElement>(); readonly #actions = new Map<TimerAction, { readonly element: HTMLButtonElement; readonly click: () => void }>();
  readonly #interval: ReturnType<typeof setInterval>; #lastTick = Date.now();
  public constructor(options: TimerOptions, policies: TimerPolicies, runtime: SemanticController<TimerState, TimerEvent, TimerCommand>) { this.#options = options; this.#policies = policies; this.#runtime = runtime; options.root.setAttribute('role', 'timer'); options.root.setAttribute('aria-live', 'off'); const intervalMs = options.intervalMs ?? 100; this.#interval = setInterval(() => { if (!this.getSnapshot().state.running) return; const now = Date.now(); const elapsedMs = now - this.#lastTick; this.#lastTick = now; this.handleEvent({ type: 'tick', elapsedMs }); }, intervalMs); this.#refresh(); }
  public getSnapshot(): RevisionSnapshot<TimerState> { return this.#runtime.getSnapshot(); }
  public handleEvent(event: TimerEvent): boolean { if (event === 'start' || event === 'resume' || event === 'restart' || (event === 'toggle' && !this.getSnapshot().state.running)) this.#lastTick = Date.now(); const result = this.#runtime.handle(event); if (!result.ok) return false; if (typeof event === 'object') this.#options.onTick?.(result.snapshot.state.valueMs, unwrap(getTimerParts(result.snapshot.state.valueMs))); for (const command of result.commands) this.#options.onComplete?.(command.valueMs); this.#refresh(); this.#options.onUpdate?.(); return true; }
  public start(): boolean { return this.handleEvent('start'); } public pause(): boolean { return this.handleEvent('pause'); } public resume(): boolean { return this.handleEvent('resume'); } public reset(): boolean { return this.handleEvent('reset'); } public restart(): boolean { return this.handleEvent('restart'); }
  public setItemAttributes(element: HTMLElement, type: TimerItemType): void { this.#items.set(type, element); element.dataset['timerItem'] = type; this.#refresh(); }
  public setActionAttributes(element: HTMLButtonElement, action: TimerAction): void { const previous = this.#actions.get(action); if (previous !== undefined) previous.element.removeEventListener('click', previous.click); const click = (): void => { this.handleEvent(action); }; element.addEventListener('click', click); this.#actions.set(action, { element, click }); this.#refresh(); }
  public disconnect(): void { clearInterval(this.#interval); for (const item of this.#actions.values()) item.element.removeEventListener('click', item.click); this.#actions.clear(); this.#items.clear(); }
  #refresh(): void { const state = this.getSnapshot().state; const parts = unwrap(getTimerParts(state.valueMs)); const progress = unwrap(getTimerProgress(state, this.#policies)); this.#options.root.dataset['state'] = state.completed ? 'complete' : state.running ? 'running' : 'idle'; this.#options.root.dataset['countdown'] = String(this.#policies.countdown === true); this.#options.root.setAttribute('aria-label', formatAccessible(parts)); if (progress === null) this.#options.root.removeAttribute('aria-valuenow'); else this.#options.root.setAttribute('aria-valuenow', String(progress)); for (const [type, element] of this.#items) element.textContent = formatPart(type, parts[type]); for (const [action, { element }] of this.#actions) { element.type = 'button'; element.dataset['timerAction'] = action; element.disabled = (action === 'pause' && !state.running) || ((action === 'start' || action === 'resume') && (state.running || state.completed)); } }
}
function formatPart(type: TimerItemType, value: number): string { return String(value).padStart(type === 'milliseconds' ? 3 : type === 'days' ? 1 : 2, '0'); }
function formatAccessible(parts: TimerParts): string { return `${parts.days} days, ${parts.hours} hours, ${parts.minutes} minutes, ${parts.seconds} seconds`; }
